# -*- coding: utf-8 -*-
"""Task1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YYFtYQcGGHWeGpEXxzkMMW4J4iO9MELl
"""

#importing librarires
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("http://bit.ly/w-data") 
df.head()

"""# Visualization """

x = df['Hours']
y = df['Scores']
plt.scatter(x,y,color='red',marker='o')
plt.title('Time vs Score')
plt.xlabel('Time in hours')
plt.ylabel('Scores')
plt.show()

"""# Spliting the dataset into testing & training"""

x = df.iloc[:,:-1].values
y = df.iloc[:,1].values
print(x)
print(y)

import sklearn
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.25,random_state=5)

"""# Creating simple linear model"""

from sklearn.linear_model import LinearRegression
model = LinearRegression()
mymodel = model.fit(x_train,y_train)

"""# Prediction

"""

# predicted value
y_pred = mymodel.predict(x_test)
y_pred

# actual value
y_test

# actual vs predicted value
dataset = pd.DataFrame({'Actual': y_test , 'Predicted': y_pred})
dataset

mymodel.predict([[6]])

mymodel.coef_

mymodel.intercept_

plt.scatter(x_train,y_train,color='red')
plt.plot(x_train,mymodel.predict(x_train))
plt.show()